
version: '3.5'

services:
  api:
    restart: always
    build: .
    ports:
      - 4000:4000
    depends_on:
      - postgres-compose
    profiles:
      - infra
      - default
    volumes:
    - .:/usr/src/app
    networks:
      - compose-network

  postgres-compose:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: postgres
    profiles:
      - infra
      - dev
      - default
    ports:
      - "5115:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - compose-network
      
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    profiles:
      - dev
      - default
    ports:
      - "5050:80"
    depends_on:
      - postgres-compose
    networks:
      - compose-network

networks: 
  compose-network:
    driver: bridge
