
version: '3.5'

services:
  api:
    restart: always
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres-compose
    profiles:
      - infra
      - default
    volumes:
    - .:/usr/src/app
    networks:
      - compose-network

  postgres-compose:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    profiles:
      - infra
      - dev
      - default
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - compose-network
      
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    profiles:
      - dev
      - default
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - postgres-compose
    networks:
      - compose-network

networks: 
  compose-network:
    driver: bridge
